[features]
seeds = true
skip-lint = false
[programs.localnet]
disco ="2c4WTKr4rQ5xEdeQVoaHGb9sBXhbyRXBKi6qLbt5SKGA"

[test.validator]
url = "https://api.devnet.solana.com"
[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"


[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/dayana/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
